name: Build API Docs
on: [push, pull_request]
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - uses: HaoZeke/doxyYoda@v0.1.0
#         with:
#          cppreference-tag: true
      - run: sudo apt-get install -y doxygen graphviz
      - run: |
         cd docs && ls -l
         make
         ls -l
#       doxygen Doxyfile-this.in
         
      - name: Archive artifact
        shell: sh
        if: runner.os == 'Linux'
        run: |
          cd docs
          tar \
          --dereference --hard-dereference \
          --exclude=.git \
          --exclude=.github \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          --directory=html .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error         
  # deploy
  deploy:
    needs: build_docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

