name: Build API Docs
on: [push, pull_request]
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: HaoZeke/doxyYoda@v0.1.0
        with:
           cppreference-tag: true   # optional: download cppreference tag file
      - run: sudo apt-get install -y doxygen graphviz
      - run: cd docs && ls -l && doxygen Doxyfile-this.in && ls -l
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html

  deploy:
    needs: build_docs
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v4
      - uses: actions/deploy-pages@v4
